# Data processing / augmentation
data_yaml_path: "src/config/dfire.yaml"

imgsz: 832

mosaic_prob: 1.0
close_mosaic_epoch: 10

mixup_prob: 0.1

hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4

degrees: 10
translate: 0.1
scale: 0.5
fliplr: 0.5

# Training
learning_rate: 0.001
epochs: 100
batch_size: 8
optimizer: "AdamW"
shuffle_data: True
num_workers: 8
weight_decay: 0.0005
warmup_epochs: 3
cos_lr: true

device: "cuda"

# Logger
log_folder_path: "src/logs"
log_level: "INFO"

# Tensorboard
tensorboard_log_dir: "runs/training"

# Inference
model_path: runs/detect/runs/training/yolov8m_finetune_20260520-113028/weights/best.pt
conf_threshold: 0.3

# Image inference
image_folder_path: "data/dataset/raw/test/images"
image_name: "WEB10751.jpg"
random_image: True
stop_after_one: False

# Video inference
video_path: "data/video_test/firefighter_pov_3.mp4"
show_video: True
save_video: True

# Main pipeline
do_train: False
do_inference_image: False
do_inference_video: True

